# Generated by Django 4.1 on 2022-08-29 19:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('name_ru', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Название')),
                ('name_uk', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Ссылка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cosmetics.category')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': '5. Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(db_index=True, default=1000, unique=True, verbose_name='Номер заявки')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('author_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('author_email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('author_surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('delivery_company', models.CharField(choices=[('np', 'Новая Почта'), ('ukrp', 'Укрпочта'), ('pickup', 'Самовывоз')], default='np', max_length=20, verbose_name='Новая Почта')),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город доставки')),
                ('delivery_way', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отделение/Почтомат')),
                ('delivery_point', models.CharField(blank=True, max_length=300, null=True, verbose_name='Отделение доставки')),
                ('way_of_payment', models.CharField(choices=[('card', 'Оплата на карту'), ('cash', 'Наличные средства'), ('cod', 'Наложенный платёж')], default='card', max_length=20, verbose_name='Вид оплаты')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждён'), ('considering', 'На рассмотрении'), ('paid', 'Оплачен'), ('rejected', 'Отклонён')], default='considering', max_length=20)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': '1. Заказы',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название')),
                ('name_uk', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Ссылка')),
                ('description', ckeditor.fields.RichTextField(max_length=7500, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(max_length=7500, null=True, verbose_name='Описание')),
                ('description_uk', ckeditor.fields.RichTextField(max_length=7500, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая Цена')),
                ('vendor_code', models.PositiveIntegerField(db_index=True, default=1000, unique=True, verbose_name='Артикул (код товара)')),
                ('warehouse_amount', models.PositiveIntegerField(default='1', verbose_name='Кол-во товара на складе')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('country_ru', models.CharField(max_length=200, null=True, verbose_name='Страна')),
                ('country_uk', models.CharField(max_length=200, null=True, verbose_name='Страна')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Производитель')),
                ('active_components', models.CharField(blank=True, max_length=500, null=True, verbose_name='Активные компоненты')),
                ('active_components_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Активные компоненты')),
                ('active_components_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Активные компоненты')),
                ('purpose', models.CharField(blank=True, max_length=200, null=True, verbose_name='Предназначение')),
                ('purpose_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Предназначение')),
                ('purpose_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Предназначение')),
                ('skin_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип кожи')),
                ('skin_type_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип кожи')),
                ('skin_type_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип кожи')),
                ('how_to_use', models.TextField(blank=True, max_length=7500, null=True, verbose_name='Способ применения')),
                ('how_to_use_ru', models.TextField(blank=True, max_length=7500, null=True, verbose_name='Способ применения')),
                ('how_to_use_uk', models.TextField(blank=True, max_length=7500, null=True, verbose_name='Способ применения')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём')),
                ('measure', models.CharField(blank=True, choices=[('ml', 'мл'), ('mg', 'мг'), ('g', 'г'), ('l', 'л'), ('kg', 'кг'), ('thing', 'шт')], default='ml', max_length=20, null=True)),
                ('status', models.CharField(choices=[('present', 'Товар есть ✅'), ('not_present', 'Товара нет ❌'), ('waiting', 'Ожидается')], default='present', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.category', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': '3. Товары',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.product')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': '2. Товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetics.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': '4. Фотографии товаров',
                'ordering': ['-product'],
            },
        ),
    ]
