# Generated by Django 3.2.10 on 2022-09-14 06:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0006_auto_20220914_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyskinblog',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Содержание post'a"),
        ),
        migrations.AddField(
            model_name='whyskinblog',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Содержание post'a"),
        ),
        migrations.AddField(
            model_name='whyskinblog',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='whyskinblog',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
